In [1]:
import numpy as np
import pandas as pd
import os

Пишем общий класс, который объединяет все файлы в нужных форматах

In [2]:
class ConvertToObject:
    '''
    Class of all object.
    '''
    

    def to_xml(self, path_file, index = -1):
        # get path of file and open file in xml. After put in dict
        data = pd.read_xml(path_file)
        if index == -1:
            self.dict_obj[path_file] = data
        else:
            self.dict_obj[self.name_files[index]] = data

    def to_csv(self, path_file, index = -1):
        # get path of file and open file in csv. After put in dict
        data = pd.read_csv(path_file)
        if index == -1:
            self.dict_obj[path_file] = data
        else:
            self.dict_obj[self.name_files[index]] = data

    def to_xls(self, path_file, index = -1):
        # get path of file and open file in xls. After put in dict
        data = pd.read_excel(path_file)

        # убираем не нужные данные в таблице
        data = data.iloc[2:, :]
        data.drop(data.columns[[1,2,3]], axis=1 ,inplace=True)
        
        data.index = data.iloc[:, 0].tolist()
        data.drop(data.columns[[0]], axis=1 ,inplace=True)
        
        # ставим год наверх
        data.columns = data.iloc[0, :].astype(int).tolist()
        data = data.iloc[1:, :]

        if index == -1:
            self.dict_obj[path_file] = data
        else:
            self.dict_obj[self.name_files[index]] = data

        

    def __init__(self):
        self.path_files = []
        self.name_files = []
        self.dict_obj = dict()


        to_directory = os.getcwd() + "/datasets/"
        self.name_files = os.listdir(to_directory)

        for i in range(len(self.name_files)):
            self.path_files.append(os.path.join(to_directory, self.name_files[i]))
            
            end_of_namefiles = self.name_files[i][-3:]

            if end_of_namefiles == "xls":
                self.to_xls(self.path_files[i], i)
            elif end_of_namefiles == "xml":
                self.to_xml(self.path_files[i], i)
            elif end_of_namefiles == "csv":
                self.to_csv(self.path_files[i], i)



obj = ConvertToObject()

Здесь уже надо обработать каждый файл по отдельности((((

In [3]:
db = obj.dict_obj.copy()

In [28]:
# sample_1 = db["cost-of-living.csv"]
# sample_1

In [5]:
sample_2 = db["happiness2017.csv"]
sample_2.index = sample_2.iloc[:, 0].tolist()
sample_2.drop(sample_2.columns[[0]], axis=1, inplace=True)
sample_2

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...
Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

In [6]:
sample_3 = db["patenti.csv"]
sample_3.drop(sample_3.columns[[1,2,3,-1]], axis=1 ,inplace=True)
sample_3.index = sample_3.iloc[:, 0].tolist()
sample_3.drop(sample_3.columns[[0]], axis=1 ,inplace=True)
sample_3.columns = sample_3.columns.map(int)
sample_3

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Western and Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,85.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.0,43.0,29.0,5.0,16.0,15.0,NaN,60.0,60.0,NaN
South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,608.0,638.0,802.0,889.0,704.0,728.0,657.0,567.0,542.0,NaN
Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,13.0,14.0,20.0,15.0,12.0,11.0,2.0,16.0,NaN
Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,8.0,NaN,NaN,NaN,NaN,NaN

In [7]:
YEAR = [2013, 2014, 2015, 2016, 2017]

GLOBAL_DATASET_YEAR = dict()

for year in YEAR:
    GLOBAL_DATASET_YEAR[year] = pd.DataFrame()
    for name in obj.name_files:
        end_of_name = name[-3:]
        if end_of_name == "xls":
            temp = obj.dict_obj[name][year].rename(name)
            GLOBAL_DATASET_YEAR[year] = pd.concat([GLOBAL_DATASET_YEAR[year], temp], axis=1)
    GLOBAL_DATASET_YEAR[year] = pd.concat([GLOBAL_DATASET_YEAR[year], sample_3[year].rename("patenti.csv")], axis=1)
    GLOBAL_DATASET_YEAR[year] = GLOBAL_DATASET_YEAR[year].join(sample_2["Happiness.Score"], how='outer')

In [8]:
GLOBAL_DATASET_YEAR[2017]

,nakoplenia_ludei.xls,rashodi_na_med.xls,chislo_ubistv.xls,inflazia.xls,nalogi.xls,procent_tryd_naselenia.xls,trati_na_obraz.xls,rogdaemost.xls,voennie_trati.xls,bezrabotiza.xls,vvp_pps_na_dyshy.xls,vvp.xls,patenti.csv,Happiness.Score
Afghanistan,NaN,12.620817,6.678401,4.975952,71.400000,90.543094,3.373310,37.342000,0.945227,NaN,2096.093111,1.889635e+10,NaN,3.794
Africa Eastern and Southern,19.969403,6.317424,NaN,6.399343,43.068000,83.930999,4.862555,34.892547,1.484722,NaN,3635.564622,1.030482e+12,NaN,NaN
Africa Western and Central,17.955235,3.789624,NaN,1.764635,50.472727,88.268982,3.430220,37.881661,0.883374,NaN,4045.303263,6.837480e+11,NaN,NaN
Albania,16.529364,5.012636,2.010978,2.060598,37.300000,46.723001,3.611730,10.870000,1.108696,NaN,12770.987862,1.301969e+10,16.0,4.644
Algeria,38.726069,6.279384,NaN,5.591116,66.100000,54.679122,6.505380,24.755000,5.924383,0.534320,11809.483033,1.700970e+11,149.0,5.872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
World,26.583623,9.764235,5.906906,2.192010,40.353968,55.113673,4.085540,18.699856,2.173431,2.133632,16155.824378,8.140950e+13,2243300.0,NaN
Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.593
"Yemen, Rep.",NaN,NaN,NaN,NaN,26.600000,78.175060,NaN,32.713000,NaN,NaN,NaN,2.684223e+10,15.0,NaN
Zambia,36.252465,4.376977,NaN,6.577312,15.600000,87.051023,3.729640,36.601000,1.309596,NaN,3395.479686,2.587360e+10,12.0,4.514
Zimbabwe,-2.682417,7.469752,NaN,0.893962,31.600000,83.101286,5.818780,32.516000,0.387831,NaN,2331.780833,1.758489e+10,NaN,3.875

In [9]:
for year in YEAR:
    GLOBAL_DATASET_YEAR[year] = GLOBAL_DATASET_YEAR[year].loc[np.intersect1d(GLOBAL_DATASET_YEAR[year].index.tolist(), sample_2.index.tolist()), :]

In [10]:
GLOBAL_DATASET_YEAR[2017]

,nakoplenia_ludei.xls,rashodi_na_med.xls,chislo_ubistv.xls,inflazia.xls,nalogi.xls,procent_tryd_naselenia.xls,trati_na_obraz.xls,rogdaemost.xls,voennie_trati.xls,bezrabotiza.xls,vvp_pps_na_dyshy.xls,vvp.xls,patenti.csv,Happiness.Score
Afghanistan,NaN,12.620817,6.678401,4.975952,71.4,90.543094,3.37331,37.342,0.945227,NaN,2096.093111,1.889635e+10,NaN,3.794
Albania,16.529364,5.012636,2.010978,2.060598,37.3,46.723001,3.61173,10.870,1.108696,NaN,12770.987862,1.301969e+10,16.0,4.644
Algeria,38.726069,6.279384,NaN,5.591116,66.1,54.679122,6.50538,24.755,5.924383,0.53432,11809.483033,1.700970e+11,149.0,5.872
Angola,23.055848,2.791503,NaN,29.842578,49.1,93.013489,2.46688,40.810,2.507985,NaN,7216.061373,6.897277e+10,NaN,3.795
Argentina,13.068849,10.442255,5.273443,NaN,106.0,55.611239,5.45432,16.206,0.856138,0.55631,23597.117753,6.436287e+11,393.0,6.599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.250
Vietnam,28.856869,4.712834,NaN,3.520257,38.1,44.182809,4.08554,16.100,2.267970,0.52674,9050.688534,2.813536e+11,592.0,5.074
Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.593
Zambia,36.252465,4.376977,NaN,6.577312,15.6,87.051023,3.72964,36.601,1.309596,NaN,3395.479686,2.587360e+10,12.0,4.514
Zimbabwe,-2.682417,7.469752,NaN,0.893962,31.6,83.101286,5.81878,32.516,0.387831,NaN,2331.780833,1.758489e+10,NaN,3.875

In [11]:
for year in YEAR:
    GLOBAL_DATASET_YEAR[year] = GLOBAL_DATASET_YEAR[year].fillna(GLOBAL_DATASET_YEAR[year].mean())

In [12]:
GLOBAL_DATASET_YEAR[2017]

,nakoplenia_ludei.xls,rashodi_na_med.xls,chislo_ubistv.xls,inflazia.xls,nalogi.xls,procent_tryd_naselenia.xls,trati_na_obraz.xls,rogdaemost.xls,voennie_trati.xls,bezrabotiza.xls,vvp_pps_na_dyshy.xls,vvp.xls,patenti.csv,Happiness.Score
Afghanistan,22.739702,12.620817,6.678401,4.975952,71.400000,90.543094,3.373310,37.342000,0.945227,1.024865,2096.093111,1.889635e+10,19947.561224,3.794
Albania,16.529364,5.012636,2.010978,2.060598,37.300000,46.723001,3.611730,10.870000,1.108696,1.024865,12770.987862,1.301969e+10,16.000000,4.644
Algeria,38.726069,6.279384,6.897430,5.591116,66.100000,54.679122,6.505380,24.755000,5.924383,0.534320,11809.483033,1.700970e+11,149.000000,5.872
Angola,23.055848,2.791503,6.897430,29.842578,49.100000,93.013489,2.466880,40.810000,2.507985,1.024865,7216.061373,6.897277e+10,19947.561224,3.795
Argentina,13.068849,10.442255,5.273443,5.692508,106.000000,55.611239,5.454320,16.206000,0.856138,0.556310,23597.117753,6.436287e+11,393.000000,6.599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,22.739702,6.694959,6.897430,5.692508,39.461194,59.921943,4.431968,20.317654,1.789780,1.024865,21682.144768,5.506601e+11,19947.561224,5.250
Vietnam,28.856869,4.712834,6.897430,3.520257,38.100000,44.182809,4.085540,16.100000,2.267970,0.526740,9050.688534,2.813536e+11,592.000000,5.074
Yemen,22.739702,6.694959,6.897430,5.692508,39.461194,59.921943,4.431968,20.317654,1.789780,1.024865,21682.144768,5.506601e+11,19947.561224,3.593
Zambia,36.252465,4.376977,6.897430,6.577312,15.600000,87.051023,3.729640,36.601000,1.309596,1.024865,3395.479686,2.587360e+10,12.000000,4.514
Zimbabwe,-2.682417,7.469752,6.897430,0.893962,31.600000,83.101286,5.818780,32.516000,0.387831,1.024865,2331.780833,1.758489e+10,19947.561224,3.875

In [13]:
for year in YEAR:
    GLOBAL_DATASET_YEAR[year].index.name = "COUNTRY"
    GLOBAL_DATASET_YEAR[year].drop(["Congo (Brazzaville)","Russia", "Slovakia", 
                     "Somalia", "South Korea", "Syria", 
                     "Taiwan Province of China", "Turkey", "Venezuela", 
                     "Yemen", "Congo (Kinshasa)", "Czech Republic", "Egypt",
                    "China", "Iran", "Ivory Coast", "Kyrgyzstan",
                     "Macedonia", "North Cyprus", "Palestinian Territories"], axis=0, inplace=True)

In [14]:
for year in YEAR:
    GLOBAL_DATASET_YEAR[year]["YEAR"] = year*np.ones(len(GLOBAL_DATASET_YEAR[year]), dtype=int)

In [15]:
GLOBAL_DATASET_YEAR[2017]

,nakoplenia_ludei.xls,rashodi_na_med.xls,chislo_ubistv.xls,inflazia.xls,nalogi.xls,procent_tryd_naselenia.xls,trati_na_obraz.xls,rogdaemost.xls,voennie_trati.xls,bezrabotiza.xls,vvp_pps_na_dyshy.xls,vvp.xls,patenti.csv,Happiness.Score,YEAR
COUNTRY,,,,,,,,,,,,,,,
Afghanistan,22.739702,12.620817,6.678401,4.975952,71.4,90.543094,3.37331,37.342,0.945227,1.024865,2096.093111,1.889635e+10,19947.561224,3.794,2017
Albania,16.529364,5.012636,2.010978,2.060598,37.3,46.723001,3.61173,10.870,1.108696,1.024865,12770.987862,1.301969e+10,16.000000,4.644,2017
Algeria,38.726069,6.279384,6.897430,5.591116,66.1,54.679122,6.50538,24.755,5.924383,0.534320,11809.483033,1.700970e+11,149.000000,5.872,2017
Angola,23.055848,2.791503,6.897430,29.842578,49.1,93.013489,2.46688,40.810,2.507985,1.024865,7216.061373,6.897277e+10,19947.561224,3.795,2017
Argentina,13.068849,10.442255,5.273443,5.692508,106.0,55.611239,5.45432,16.206,0.856138,0.556310,23597.117753,6.436287e+11,393.000000,6.599,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uruguay,15.915229,8.821792,8.234775,6.218094,41.8,55.473795,4.47097,12.579,1.956923,0.448490,23106.998194,6.423397e+10,23.000000,6.454,2017
Uzbekistan,32.154768,5.076799,1.849200,13.875743,38.3,50.062409,5.03282,22.100,1.789780,0.148340,6840.709860,6.208132e+10,357.000000,5.971,2017
Vietnam,28.856869,4.712834,6.897430,3.520257,38.1,44.182809,4.08554,16.100,2.267970,0.526740,9050.688534,2.813536e+11,592.000000,5.074,2017
Zambia,36.252465,4.376977,6.897430,6.577312,15.6,87.051023,3.72964,36.601,1.309596,1.024865,3395.479686,2.587360e+10,12.000000,4.514,2017
Zimbabwe,-2.682417,7.469752,6.897430,0.893962,31.6,83.101286,5.81878,32.516,0.387831,1.024865,2331.780833,1.758489e+10,19947.561224,3.875,2017

In [16]:
GLOBAL_DATASET = pd.concat(GLOBAL_DATASET_YEAR.values())

In [25]:
GLOBAL_DATASET = GLOBAL_DATASET.sort_values(["COUNTRY", "YEAR"])

In [26]:
GLOBAL_DATASET

,nakoplenia_ludei.xls,rashodi_na_med.xls,chislo_ubistv.xls,inflazia.xls,nalogi.xls,procent_tryd_naselenia.xls,trati_na_obraz.xls,rogdaemost.xls,voennie_trati.xls,bezrabotiza.xls,vvp_pps_na_dyshy.xls,vvp.xls,patenti.csv,Happiness.Score,YEAR
COUNTRY,,,,,,,,,,,,,,,
Afghanistan,22.230897,8.805941,7.321481,7.385772,35.6,97.125534,3.45446,39.601,1.076950,1.022259,2062.059176,2.056449e+10,15088.308511,3.794,2013
Afghanistan,22.475371,9.528871,7.040329,4.673996,36.1,94.706697,3.69522,39.105,1.298013,0.997758,2110.829568,2.055058e+10,16001.021277,3.794,2014
Afghanistan,21.690834,10.105348,9.783922,-0.661709,36.1,93.042448,3.25580,38.803,0.994576,1.025159,2128.125938,1.999816e+10,17111.835052,3.794,2015
Afghanistan,21.489296,11.818562,6.551163,4.383892,47.9,92.012125,3.51198,37.936,0.956772,1.025911,2023.834656,1.801956e+10,18774.313725,3.794,2016
Afghanistan,22.739702,12.620817,6.678401,4.975952,71.4,90.543094,3.37331,37.342,0.945227,1.024865,2096.093111,1.889635e+10,19947.561224,3.794,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,-5.481515,7.110148,7.321481,1.634950,34.1,86.445433,5.99598,36.246,1.868420,1.022259,2522.038124,1.909102e+10,15088.308511,3.875,2013
Zimbabwe,-4.790795,8.133525,7.040329,-0.197785,31.4,85.875504,6.13835,35.122,1.888080,0.997758,2561.728799,1.949552e+10,16001.021277,3.875,2014
Zimbabwe,-10.086841,7.452066,7.089839,-2.430968,31.6,85.083365,5.81279,33.960,1.886876,1.025159,2615.090301,1.996312e+10,9.000000,3.875,2015
Zimbabwe,-4.967818,7.675163,7.414828,-1.543670,31.6,84.112216,5.47262,33.171,1.720991,1.025911,2724.452742,2.054868e+10,8.000000,3.875,2016
Zimbabwe,-2.682417,7.469752,6.897430,0.893962,31.6,83.101286,5.81878,32.516,0.387831,1.024865,2331.780833,1.758489e+10,19947.561224,3.875,2017

In [27]:
GLOBAL_DATASET.to_csv(os.getcwd()+"/global_data.csv", index=True, sep=';')