In [1]:
import numpy as np
import pandas as pd
import os

Пишем общий класс, который объединяет все файлы в нужных форматах

In [2]:
class ConvertToObject:
    '''
    Class of all object.
    '''
    

    def to_xml(self, path_file, index = -1):
        # get path of file and open file in xml. After put in dict
        data = pd.read_xml(path_file)
        if index == -1:
            self.dict_obj[path_file] = data
        else:
            self.dict_obj[self.name_files[index]] = data

    def to_csv(self, path_file, index = -1):
        # get path of file and open file in csv. After put in dict
        data = pd.read_csv(path_file)
        if index == -1:
            self.dict_obj[path_file] = data
        else:
            self.dict_obj[self.name_files[index]] = data

    def to_xls(self, path_file, index = -1):
        # get path of file and open file in xls. After put in dict
        data = pd.read_excel(path_file)

        # убираем не нужные данные в таблице
        data = data.iloc[2:, :]
        data.drop(data.columns[[1,2,3]], axis=1 ,inplace=True)
        
        data.index = data.iloc[:, 0].tolist()
        data.drop(data.columns[[0]], axis=1 ,inplace=True)
        
        # ставим год наверх
        data.columns = data.iloc[0, :].astype(int).tolist()
        data = data.iloc[1:, :]

        if index == -1:
            self.dict_obj[path_file] = data
        else:
            self.dict_obj[self.name_files[index]] = data

        

    def __init__(self):
        self.path_files = []
        self.name_files = []
        self.dict_obj = dict()


        to_directory = os.getcwd() + "/datasets/"
        self.name_files = os.listdir(to_directory)

        for i in range(len(self.name_files)):
            self.path_files.append(os.path.join(to_directory, self.name_files[i]))
            
            end_of_namefiles = self.name_files[i][-3:]

            if end_of_namefiles == "xls":
                self.to_xls(self.path_files[i], i)
            elif end_of_namefiles == "xml":
                self.to_xml(self.path_files[i], i)
            elif end_of_namefiles == "csv":
                self.to_csv(self.path_files[i], i)



obj = ConvertToObject()

Здесь уже надо обработать каждый файл по отдельности((((

In [3]:
db = obj.dict_obj.copy()

In [4]:
YEAR = [2015, 2016, 2017, 2018, 2019, 2020, 2021]

In [5]:
HAPPY_DATASET = dict()

to_directory = os.getcwd() + "/archive/"
for year, name_file in enumerate(os.listdir(to_directory)):
    HAPPY_DATASET[YEAR[year]] = pd.read_csv(os.path.join(to_directory, name_file))

In [6]:
name_country_2015 = HAPPY_DATASET[2015]["Country name"]
HAPPY_DATASET[2015].rename(columns={"Ladder score" : "Happiness.Score", "Country name" : "COUNTRY"}, inplace=True)

In [7]:
name_country_2016 = HAPPY_DATASET[2016]["Country name"]
HAPPY_DATASET[2016].rename(columns={"Ladder score" : "Happiness.Score", "Country name" : "COUNTRY"}, inplace=True)

In [8]:
name_country_2017 = HAPPY_DATASET[2017]["Country or region"]
HAPPY_DATASET[2017].rename(columns={"Score" : "Happiness.Score", "Country or region" : "COUNTRY"}, inplace=True)

In [9]:
name_country_2018 = HAPPY_DATASET[2018]["Country or region"]
HAPPY_DATASET[2018].rename(columns={"Score" : "Happiness.Score", "Country or region" : "COUNTRY"}, inplace=True)

In [10]:
name_country_2019 = HAPPY_DATASET[2019]["Country"]
HAPPY_DATASET[2019].rename(columns={"Happiness Score" : "Happiness.Score", "Country" : "COUNTRY"}, inplace=True)

In [11]:
name_country_2020 = HAPPY_DATASET[2020]["Country"]
HAPPY_DATASET[2020].rename(columns={"Happiness Score" : "Happiness.Score", "Country" : "COUNTRY"}, inplace=True)

In [12]:
name_country_2021 = HAPPY_DATASET[2021]["Country"]
HAPPY_DATASET[2021].rename(columns={"Happiness.Score" : "Happiness.Score", "Country" : "COUNTRY"}, inplace=True)

In [13]:
for year in YEAR:
    HAPPY_DATASET[year].set_index("COUNTRY", inplace=True)

In [14]:
HAPPY_DATASET[2015]

,Regional indicator,Happiness.Score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
COUNTRY,,,,,,,,,,,,,,,,,,,
Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Central African Republic,Sub-Saharan Africa,3.4759,0.115183,3.701658,3.250141,6.625160,0.319460,45.200001,0.640881,0.082410,0.891807,1.972317,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
Rwanda,Sub-Saharan Africa,3.3123,0.052425,3.415053,3.209547,7.600104,0.540835,61.098846,0.900589,0.055484,0.183541,1.972317,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
Zimbabwe,Sub-Saharan Africa,3.2992,0.058674,3.414202,3.184198,7.865712,0.763093,55.617260,0.711458,-0.072064,0.810237,1.972317,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
South Sudan,Sub-Saharan Africa,2.8166,0.107610,3.027516,2.605684,7.425360,0.553707,51.000000,0.451314,0.016519,0.763417,1.972317,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
Afghanistan,South Asia,2.5669,0.031311,2.628270,2.505530,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687,1.972317,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

In [15]:
# sample_2 = db["happiness2017.csv"]
# sample_2.index = sample_2.iloc[:, 0].tolist()
# sample_2.drop(sample_2.columns[[0]], axis=1, inplace=True)
# sample_2

In [16]:
sample_3 = db["patenti.csv"]
sample_3.drop(sample_3.columns[[1,2,3,-1]], axis=1 ,inplace=True)
sample_3.index = sample_3.iloc[:, 0].tolist()
sample_3.drop(sample_3.columns[[0]], axis=1 ,inplace=True)
sample_3.columns = sample_3.columns.map(int)
sample_3

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Western and Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,85.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.0,43.0,29.0,5.0,16.0,15.0,NaN,60.0,60.0,NaN
South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,608.0,638.0,802.0,889.0,704.0,728.0,657.0,567.0,542.0,NaN
Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,13.0,14.0,20.0,15.0,12.0,11.0,2.0,16.0,NaN
Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,8.0,NaN,NaN,NaN,NaN,NaN

In [17]:
GLOBAL_DATASET_YEAR = dict()

for year in YEAR:
    GLOBAL_DATASET_YEAR[year] = pd.DataFrame()
    for name in obj.name_files:
        end_of_name = name[-3:]
        if end_of_name == "xls":
            temp = obj.dict_obj[name][year].rename(name)
            GLOBAL_DATASET_YEAR[year] = pd.concat([GLOBAL_DATASET_YEAR[year], temp], axis=1)
    GLOBAL_DATASET_YEAR[year] = pd.concat([GLOBAL_DATASET_YEAR[year], sample_3[year].rename("patenti.csv")], axis=1)
    GLOBAL_DATASET_YEAR[year] = GLOBAL_DATASET_YEAR[year].join(HAPPY_DATASET[year]["Happiness.Score"], how='outer')

In [18]:
GLOBAL_DATASET_YEAR[2018]

,nakoplenia_ludei.xls,rashodi_na_med.xls,chislo_ubistv.xls,inflazia.xls,nalogi.xls,procent_tryd_naselenia.xls,trati_na_obraz.xls,rogdaemost.xls,voennie_trati.xls,bezrabotiza.xls,vvp_pps_na_dyshy.xls,vvp.xls,patenti.csv,Happiness.Score
Afghanistan,NaN,14.126743,6.655561,0.626149,71.400000,89.091451,3.199790,36.927000,1.006746,NaN,2109.929296,1.841885e+10,NaN,3.632
Africa Eastern and Southern,19.867242,6.323236,NaN,4.720811,43.212000,83.342406,4.834590,34.611033,1.118114,NaN,3724.868177,1.016697e+12,NaN,NaN
Africa Western and Central,18.677233,3.383501,NaN,1.784050,50.695455,87.676966,3.013220,37.447087,0.905133,NaN,4160.540965,7.663597e+11,NaN,NaN
Albania,16.547233,5.232072,2.289492,2.028060,37.300000,46.914934,3.154901,10.517000,1.160545,NaN,13498.196119,1.515643e+10,15.0,4.586
Algeria,40.150062,6.163026,NaN,4.269990,66.100000,55.953864,5.866350,24.074000,5.467824,NaN,12006.010238,1.749109e+11,152.0,5.295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
World,26.726351,9.701241,5.774734,2.438737,40.291579,55.235506,4.212570,18.177567,2.151094,2.196267,16958.335122,8.646696e+13,2378500.0,NaN
Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.355
"Yemen, Rep.",NaN,NaN,NaN,NaN,26.600000,77.198481,NaN,32.305000,NaN,NaN,NaN,2.160616e+10,NaN,NaN
Zambia,41.825828,5.032715,NaN,7.494572,15.600000,85.838977,4.739750,36.040000,1.409462,NaN,3507.795230,2.631159e+10,11.0,4.377
Zimbabwe,13.923906,8.680062,NaN,10.618866,31.600000,82.123347,3.866110,32.074000,0.309323,NaN,2456.948771,3.415607e+10,NaN,3.692

In [31]:
temp = list(set(GLOBAL_DATASET_YEAR[year].index.tolist()) & set(name_country_2015.tolist()) & 
    set(name_country_2016.tolist()) & set(name_country_2017.tolist()) &
    set(name_country_2018.tolist()) & set(name_country_2019.tolist()) & 
    set(name_country_2020.tolist()) & set(name_country_2021.tolist()))

for year in YEAR:
    GLOBAL_DATASET_YEAR[year] = GLOBAL_DATASET_YEAR[year].loc[temp, :]
    GLOBAL_DATASET_YEAR[year].sort_index(inplace=True)

In [34]:
GLOBAL_DATASET_YEAR[2017]

,nakoplenia_ludei.xls,rashodi_na_med.xls,chislo_ubistv.xls,inflazia.xls,nalogi.xls,procent_tryd_naselenia.xls,trati_na_obraz.xls,rogdaemost.xls,voennie_trati.xls,bezrabotiza.xls,vvp_pps_na_dyshy.xls,vvp.xls,patenti.csv,Happiness.Score
Afghanistan,22.637618,12.620817,6.678401,4.975952,71.400000,90.543094,3.373310,37.342000,0.945227,1.036533,2096.093111,1.889635e+10,20792.840426,3.203
Albania,16.529364,5.012636,2.010978,2.060598,37.300000,46.723001,3.611730,10.870000,1.108696,1.036533,12770.987862,1.301969e+10,16.000000,4.719
Algeria,38.726069,6.279384,6.331842,5.591116,66.100000,54.679122,6.505380,24.755000,5.924383,0.534320,11809.483033,1.700970e+11,149.000000,5.211
Argentina,13.068849,10.442255,5.273443,3.811727,106.000000,55.611239,5.454320,16.206000,0.856138,0.556310,23597.117753,6.436287e+11,393.000000,6.086
Armenia,16.930340,10.362705,2.377080,0.969553,18.500000,45.593111,2.707590,13.606000,3.849731,0.227880,12509.639606,1.152746e+10,107.000000,4.559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,22.637618,6.729526,6.331842,3.811727,39.872358,58.852596,4.390335,19.455492,1.771615,1.036533,22265.438945,5.960862e+11,20792.840426,4.707
Vietnam,28.856869,4.712834,6.331842,3.520257,38.100000,44.182809,4.085540,16.100000,2.267970,0.526740,9050.688534,2.813536e+11,592.000000,5.175
Yemen,22.637618,6.729526,6.331842,3.811727,39.872358,58.852596,4.390335,19.455492,1.771615,1.036533,22265.438945,5.960862e+11,20792.840426,3.380
Zambia,36.252465,4.376977,6.331842,6.577312,15.600000,87.051023,3.729640,36.601000,1.309596,1.036533,3395.479686,2.587360e+10,12.000000,4.107
Zimbabwe,-2.682417,7.469752,6.331842,0.893962,31.600000,83.101286,5.818780,32.516000,0.387831,1.036533,2331.780833,1.758489e+10,20792.840426,3.663

In [35]:
for year in YEAR:
    GLOBAL_DATASET_YEAR[year] = GLOBAL_DATASET_YEAR[year].fillna(GLOBAL_DATASET_YEAR[year].mean())

In [36]:
GLOBAL_DATASET_YEAR[2017]

,nakoplenia_ludei.xls,rashodi_na_med.xls,chislo_ubistv.xls,inflazia.xls,nalogi.xls,procent_tryd_naselenia.xls,trati_na_obraz.xls,rogdaemost.xls,voennie_trati.xls,bezrabotiza.xls,vvp_pps_na_dyshy.xls,vvp.xls,patenti.csv,Happiness.Score
Afghanistan,22.637618,12.620817,6.678401,4.975952,71.400000,90.543094,3.373310,37.342000,0.945227,1.036533,2096.093111,1.889635e+10,20792.840426,3.203
Albania,16.529364,5.012636,2.010978,2.060598,37.300000,46.723001,3.611730,10.870000,1.108696,1.036533,12770.987862,1.301969e+10,16.000000,4.719
Algeria,38.726069,6.279384,6.331842,5.591116,66.100000,54.679122,6.505380,24.755000,5.924383,0.534320,11809.483033,1.700970e+11,149.000000,5.211
Argentina,13.068849,10.442255,5.273443,3.811727,106.000000,55.611239,5.454320,16.206000,0.856138,0.556310,23597.117753,6.436287e+11,393.000000,6.086
Armenia,16.930340,10.362705,2.377080,0.969553,18.500000,45.593111,2.707590,13.606000,3.849731,0.227880,12509.639606,1.152746e+10,107.000000,4.559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,22.637618,6.729526,6.331842,3.811727,39.872358,58.852596,4.390335,19.455492,1.771615,1.036533,22265.438945,5.960862e+11,20792.840426,4.707
Vietnam,28.856869,4.712834,6.331842,3.520257,38.100000,44.182809,4.085540,16.100000,2.267970,0.526740,9050.688534,2.813536e+11,592.000000,5.175
Yemen,22.637618,6.729526,6.331842,3.811727,39.872358,58.852596,4.390335,19.455492,1.771615,1.036533,22265.438945,5.960862e+11,20792.840426,3.380
Zambia,36.252465,4.376977,6.331842,6.577312,15.600000,87.051023,3.729640,36.601000,1.309596,1.036533,3395.479686,2.587360e+10,12.000000,4.107
Zimbabwe,-2.682417,7.469752,6.331842,0.893962,31.600000,83.101286,5.818780,32.516000,0.387831,1.036533,2331.780833,1.758489e+10,20792.840426,3.663

In [38]:
for year in YEAR:
    GLOBAL_DATASET_YEAR[year].index.name = "COUNTRY"
    GLOBAL_DATASET_YEAR[year].drop(["Congo (Brazzaville)","Russia", "Slovakia",  "South Korea",  
                                    "Turkey", "Venezuela", "Yemen", "Czech Republic", "Egypt",
                                    "China", "Iran", "Ivory Coast", "Kyrgyzstan", "Palestinian Territories"], axis=0, inplace=True)

In [39]:
for year in YEAR:
    GLOBAL_DATASET_YEAR[year]["YEAR"] = year*np.ones(len(GLOBAL_DATASET_YEAR[year]), dtype=int)

In [42]:
GLOBAL_DATASET_YEAR[2017]

,nakoplenia_ludei.xls,rashodi_na_med.xls,chislo_ubistv.xls,inflazia.xls,nalogi.xls,procent_tryd_naselenia.xls,trati_na_obraz.xls,rogdaemost.xls,voennie_trati.xls,bezrabotiza.xls,vvp_pps_na_dyshy.xls,vvp.xls,patenti.csv,Happiness.Score,YEAR
COUNTRY,,,,,,,,,,,,,,,
Afghanistan,22.637618,12.620817,6.678401,4.975952,71.4,90.543094,3.37331,37.342,0.945227,1.036533,2096.093111,1.889635e+10,20792.840426,3.203,2017
Albania,16.529364,5.012636,2.010978,2.060598,37.3,46.723001,3.61173,10.870,1.108696,1.036533,12770.987862,1.301969e+10,16.000000,4.719,2017
Algeria,38.726069,6.279384,6.331842,5.591116,66.1,54.679122,6.50538,24.755,5.924383,0.534320,11809.483033,1.700970e+11,149.000000,5.211,2017
Argentina,13.068849,10.442255,5.273443,3.811727,106.0,55.611239,5.45432,16.206,0.856138,0.556310,23597.117753,6.436287e+11,393.000000,6.086,2017
Armenia,16.930340,10.362705,2.377080,0.969553,18.5,45.593111,2.70759,13.606,3.849731,0.227880,12509.639606,1.152746e+10,107.000000,4.559,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uruguay,15.915229,8.821792,8.234775,6.218094,41.8,55.473795,4.47097,12.579,1.956923,0.448490,23106.998194,6.423397e+10,23.000000,6.293,2017
Uzbekistan,32.154768,5.076799,1.849200,13.875743,38.3,50.062409,5.03282,22.100,1.771615,0.148340,6840.709860,6.208132e+10,357.000000,6.174,2017
Vietnam,28.856869,4.712834,6.331842,3.520257,38.1,44.182809,4.08554,16.100,2.267970,0.526740,9050.688534,2.813536e+11,592.000000,5.175,2017
Zambia,36.252465,4.376977,6.331842,6.577312,15.6,87.051023,3.72964,36.601,1.309596,1.036533,3395.479686,2.587360e+10,12.000000,4.107,2017
Zimbabwe,-2.682417,7.469752,6.331842,0.893962,31.6,83.101286,5.81878,32.516,0.387831,1.036533,2331.780833,1.758489e+10,20792.840426,3.663,2017

In [43]:
GLOBAL_DATASET = pd.concat(GLOBAL_DATASET_YEAR.values())

In [44]:
GLOBAL_DATASET = GLOBAL_DATASET.sort_values(["COUNTRY", "YEAR"])

In [45]:
GLOBAL_DATASET

,nakoplenia_ludei.xls,rashodi_na_med.xls,chislo_ubistv.xls,inflazia.xls,nalogi.xls,procent_tryd_naselenia.xls,trati_na_obraz.xls,rogdaemost.xls,voennie_trati.xls,bezrabotiza.xls,vvp_pps_na_dyshy.xls,vvp.xls,patenti.csv,Happiness.Score,YEAR
COUNTRY,,,,,,,,,,,,,,,
Afghanistan,21.512335,10.105348,9.783922,-0.661709,36.1,93.042448,3.255800,38.803,0.994576,1.064793,2128.125938,1.999816e+10,18038.478261,2.5669,2015
Afghanistan,21.322787,11.818562,6.551163,4.383892,47.9,92.012125,3.511980,37.936,0.956772,1.052324,2023.834656,1.801956e+10,19944.166667,2.5230,2016
Afghanistan,22.637618,12.620817,6.678401,4.975952,71.4,90.543094,3.373310,37.342,0.945227,1.036533,2096.093111,1.889635e+10,20792.840426,3.2030,2017
Afghanistan,22.996789,14.126743,6.655561,0.626149,71.4,89.091451,3.199790,36.927,1.006746,1.072621,2109.929296,1.841885e+10,21955.589474,3.6320,2018
Afghanistan,23.053238,13.242202,6.020428,2.302373,71.4,87.649322,3.213780,36.466,1.118231,1.165593,2167.704111,1.890449e+10,22425.941860,3.5750,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,-2.682417,7.469752,6.331842,0.893962,31.6,83.101286,5.818780,32.516,0.387831,1.036533,2331.780833,1.758489e+10,20792.840426,3.6630,2017
Zimbabwe,13.923906,8.680062,6.263187,10.618866,31.6,82.123347,3.866110,32.074,0.309323,1.072621,2456.948771,3.415607e+10,21955.589474,3.6920,2018
Zimbabwe,20.231198,7.703565,6.020428,255.304991,31.6,81.207858,4.414520,31.518,0.534804,1.165593,2296.390269,2.183223e+10,22425.941860,4.6100,2019
Zimbabwe,16.452763,NaN,5.455045,557.201817,NaN,80.285255,4.657322,31.009,0.005400,1.341031,2099.320459,2.150970e+10,22405.943820,4.1930,2020
Zimbabwe,23.099484,NaN,NaN,98.546105,NaN,79.393577,3.978992,NaN,0.013530,0.132450,2323.687257,2.837124e+10,NaN,3.8750,2021

In [ ]:
GLOBAL_DATASET.to_csv(os.getcwd()+"/global_data.csv", index=True, sep=';')